name: K6 Web Test
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

permissions:
  contents: write

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  # cannot use the k6 docker image because it does not allow executing shell commands
    - name: Install k6 in Ubuntu
      if: steps.cache-k6.outputs.cache-hit != 'true'
      run: |  
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
    
    - name: Install chrome
      run: |  
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt update && sudo apt install -y google-chrome-stable

    - name: Make the script files executable
      run: chmod +x run-tests.sh

    - name: Test bash-wrapper
      run: |
        ./run-tests.sh

    - run: ls & mkdir report & mv index.html report
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: relatorio de testes de performance Web
        path: report

    - name: Publish report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: report
